from Settings.game_setting import X, O, EMPTY

# Alpha-Beta pruning setting
MAX_TREE_DEPTH_LEVEL = 2

# Tạo ra các bước di chuyển
EXPANSION_RANGE = 2

# Đánh giá điểm số
SCORE_4_UNBLOCKED_PIECES = 50007
SCORE_3_UNBLOCKED_PIECES = 5005
SCORE_2_UNBLOCKED_PIECES = 103
SCORE_1_UNBLOCKED_PIECES = 11

SCORE_5_BLOCKED_PIECES = 1000009 # WIN
SCORE_4_BLOCKED_PIECES = 6007
SCORE_3_BLOCKED_PIECES = 185

# Kiếm tra trước khi sử dụng Alpha-Beta pruning 
ENABLE_HIGH_IMPACT_MOVE = True

HIGH_IMPACT_MOVE_THRESHOLD = 15440 # 15440
# => giảm giá trị này có thế làm giảm thời gian tính toán của AI nvaf cũng giảm chất lượng của nước đi

# Đánh giá mẫu
X_6_PATTERNS = [
    [EMPTY, X, X, X, X, EMPTY],

    [EMPTY, EMPTY, X, X, X, EMPTY],
    [EMPTY, X, EMPTY, X, X, EMPTY],
    [EMPTY, X, X, EMPTY, X, EMPTY],
    [EMPTY, X, X, X, EMPTY, EMPTY],

    [EMPTY, EMPTY, EMPTY, X, X, EMPTY],
    [EMPTY, X, EMPTY, EMPTY, X, EMPTY],
    [EMPTY, X, X, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, X, X, EMPTY, EMPTY],
    [EMPTY, EMPTY, X, EMPTY, X, EMPTY],
    [EMPTY, X, EMPTY, X, EMPTY, EMPTY],

    [EMPTY, EMPTY, EMPTY, EMPTY, X, EMPTY],
    [EMPTY, EMPTY, EMPTY, X, EMPTY, EMPTY],
    [EMPTY, EMPTY, X, EMPTY, EMPTY, EMPTY],
    [EMPTY, X, EMPTY, EMPTY, EMPTY, EMPTY],
]

X_6_PATTERNS_SCRES =[
    SCORE_4_UNBLOCKED_PIECES, 

    SCORE_3_UNBLOCKED_PIECES, 
    SCORE_3_UNBLOCKED_PIECES, 
    SCORE_3_UNBLOCKED_PIECES, 

    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 

    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
]

X_5_PATTERNS = [
    [X, X, X, X, X],

    [EMPTY, X, X, X, X],
    [X, EMPTY, X, X, X],
    [X, X, EMPTY, X, X],
    [X, X, X, EMPTY, X],
    [X, X, X, X, EMPTY],

    [EMPTY, EMPTY, X, X, X],
    [X, EMPTY, EMPTY, X, X],
    [X, X, EMPTY, EMPTY, X],
    [X, X, X, EMPTY, EMPTY],
    [EMPTY, X, EMPTY, X, X],
    [X, EMPTY, X, EMPTY, X],
    [X, X, EMPTY, X, EMPTY],
    [EMPTY, X, X, EMPTY, X],
    [X, EMPTY, X, X, EMPTY],
    [EMPTY, X, X, X, EMPTY],
]

X_5_PATTERNS_SCORES = [
    SCORE_5_BLOCKED_PIECES,

    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,

    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
]

X_ENDGAME_PATTERN = [X, X, X, X, X]

O_6_PATTERNS = [
    [EMPTY, O, O, O, O, EMPTY],

    [EMPTY, EMPTY, O, O, O, EMPTY],
    [EMPTY, O, EMPTY, O, O, EMPTY],
    [EMPTY, O, O, EMPTY, O, EMPTY],
    [EMPTY, O, O, O, EMPTY, EMPTY],

    [EMPTY, EMPTY, EMPTY, O, O, EMPTY],
    [EMPTY, O, EMPTY, EMPTY, O, EMPTY],
    [EMPTY, O, O, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, O, O, EMPTY, EMPTY],
    [EMPTY, EMPTY, O, EMPTY, O, EMPTY],
    [EMPTY, O, EMPTY, O, EMPTY, EMPTY],

    [EMPTY, EMPTY, EMPTY, EMPTY, O, EMPTY],
    [EMPTY, EMPTY, EMPTY, O, EMPTY, EMPTY],
    [EMPTY, EMPTY, O, EMPTY, EMPTY, EMPTY],
    [EMPTY, O, EMPTY, EMPTY, EMPTY, EMPTY],
]

O_6_PATTERNS_SCRES =[
    SCORE_4_UNBLOCKED_PIECES, 

    SCORE_3_UNBLOCKED_PIECES, 
    SCORE_3_UNBLOCKED_PIECES, 
    SCORE_3_UNBLOCKED_PIECES, 

    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 
    SCORE_2_UNBLOCKED_PIECES, 

    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
    SCORE_1_UNBLOCKED_PIECES, 
]

O_5_PATTERNS = [
    [O, O, O, O, O],

    [EMPTY, O, O, O, O],
    [O, EMPTY, O, O, O],
    [O, O, EMPTY, O, O],
    [O, O, O, EMPTY, O],
    [O, O, O, O, EMPTY],

    [EMPTY, EMPTY, O, O, O],
    [O, EMPTY, EMPTY, O, O],
    [O, O, EMPTY, EMPTY, O],
    [O, O, O, EMPTY, EMPTY],
    [EMPTY, O, EMPTY, O, O],
    [O, EMPTY, O, EMPTY, O],
    [O, O, EMPTY, O, EMPTY],
    [EMPTY, O, O, EMPTY, O],
    [O, EMPTY, O, O, EMPTY],
    [EMPTY, O, O, O, EMPTY],
]

O_5_PATTERNS_SCORES = [
    SCORE_5_BLOCKED_PIECES,

    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,
    SCORE_4_BLOCKED_PIECES,

    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
    SCORE_3_BLOCKED_PIECES,
]

O_ENDGAME_PATTERN = [O, O, O, O, O]