import Settings.game_settings as game_settings

FPS = 60

COLOR_WHITE = (255, 255, 255)
COLOR_BLACK = (0, 0, 0)
COLOR_RED = (255, 0, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_YELLOW = (33, 156, 144)
COLOR_GREEN = (0, 180, 0)
COLOR_BLUE_VIOLET = (138, 43, 226)
COLOR_WHITE_VANILLA = (244, 240, 220)
COLOR_CYAN = (57, 183, 237)
COLOR_DARK_GREEN = (0, 100, 0)
COLOR_WIN = (18, 72, 107)
COLOR_ROUND = (116, 142, 99)
SQUARE_SIZE = 35 

# CELL
O_CELL_BORDER = 4
O_RADIUS = SQUARE_SIZE/2
O_LINE_THICKNESS = 4

X_CELL_BORDER = 6
X_LINE_THICKNESS = 6

X_COLOR = COLOR_RED
O_COLOR = COLOR_BLUE
O_LAST_MOVE_COLOR = COLOR_BLUE_VIOLET
X_LAST_MOVE_COLOR = COLOR_BLUE_VIOLET

def get_last_move_color(player):
    if(player == game_settings.O):
        return O_LAST_MOVE_COLOR
    if(player == game_settings.X):
        return X_LAST_MOVE_COLOR
    
BORDER_SIZE = 5

NEW_GAME_INFO_TEXT = 'NEW GAME'
COM_TURN_INFO_TEXT = 'AI TURN'
HUMAN_TURN_INFO_TEXT = 'YOUR TURN'
COM_WIN_INFO_TEXT = 'AI WIN'
HUMAN_WIN_INFO_TEXT = 'HUMAN WIN'
DRAW_INFO_TEXT = 'DRAW!'

X_TURN_INFO_TEXT = 'X TURN'
O_TURN_INFO_TEXT = 'O TURN'
X_WIN_INFO_TEXT = 'X WIN'
O_WIN_INFO_TEXT = 'O WIN'

# BOARD
SQUARE_SIZE = 35

CENTER_CIRCLE_RADIUS = 8

BOARD_WIDTH = game_settings.BOARD_COL_COUNT * SQUARE_SIZE
BOARD_HEIGHT = game_settings.BOARD_ROW_COUNT * SQUARE_SIZE 

BOARD_POS_X_MIN = BORDER_SIZE +15
BOARD_POS_Y_MIN = BORDER_SIZE + 30 + BORDER_SIZE 
BOARD_POS_X_MAX = BOARD_POS_X_MIN + BOARD_WIDTH +15
BOARD_POS_Y_MAX = BOARD_HEIGHT + BOARD_HEIGHT 

BOARD_COLOR = COLOR_WHITE_VANILLA
BOARD_LINE_WIDTH = 2

# WINDOW
WINDOW_WIDTH = 850
WINDOW_HEIGHT = 600
WINDOW_TITLE = 'GAME CARO'

# NEW GAME BUTTON

# Đặt nút new gane bên phải của màn hình
NEWGAME_BUTTON_POS_X_MIN = 630
NEWGAME_BUTTON_POS_X_MAX = 740
NEWGAME_BUTTON_POS_Y_MIN = 470
NEWGAME_BUTTON_POS_Y_MAX = 510

NEW_GAME_BUTTON_POS = (NEWGAME_BUTTON_POS_X_MIN, NEWGAME_BUTTON_POS_Y_MIN)


HOME_BUTTON_POS_X_MIN = 640
HOME_BUTTON_POS_X_MAX = 740
HOME_BUTTON_POS_Y_MIN = 510
HOME_BUTTON_POS_Y_MAX = 550

HOME_BUTTON_POS = (HOME_BUTTON_POS_X_MIN, HOME_BUTTON_POS_Y_MIN)

